### ISSUE TITLE
Chars müssen hart chillen können

### ISSUE THREAD

**Issue by Cybermuell** [Cradac/ldjam56#1]
Aktuell fehlt noch ein custom emoji wenn die chars an ihrem PoI chillen.
Optimal was mit Sonennbrille 😎.

**Comment by Cradac** [comment]
obviously low effort, see typo

**Comment by DorianSnowball** [comment]
Wir haben weder einen Nord-Pol noch einen Süd-Pol im Spiel. Won't Fix
